project:
  type: website
  output-dir: docs 

website:
  title: "Hala Arar | Data Science Portfolio"
  navbar:
    background: "#1E88E5"  
    foreground: "#FFFFFF"  
    left:
      - text: Projects
        menu:
          - href: projects.qmd
            text: All Projects
          - href: projects/health_science_calculator.qmd
            text: Health Science Calculator
          - href: projects/bank_marketing_predictions.qmd
            text: Bank Marketing Prediction
          - href: projects/nyc_arrest_dashboard.qmd
            text: NYC Arrest Dashboard
          - href: projects/data_science_starter_kit.qmd
            text: Data Science Starter Kit
          - href: projects/Antibacterial_effects.qmd
            text: Natural Antibiotics Study
      - href: Education.qmd
        text: Education

    right:
      - icon: github
        href: https://github.com/halaarar
      - icon: linkedin
        href: https://www.linkedin.com/in/hala-arar-9931a615b/
      - icon: envelope
        href: mailto:halaosama92@yahoo.com

format:
  html:
    theme: minty
    css: styles.css
    toc: false
    page-layout: full
    highlight-style: monokai
    fontfamily: "Poppins, sans-serif" 
    fontsize: 17px
