project:
  type: website

website:
  title: "Hala Arar"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Education.qmd
        text: Education
      - href: projects.qmd
        text: Projects
      - href: Work_Experience.qmd
        text: Work Experience
      - href: Extracurriculars.qmd
        text: Extracurriculars
      - href: Resume.qmd
        text: Resume
    right:
      - icon: github
        href: https://github.com/halaarar
      - icon: linkedin
        href: https://www.linkedin.com/in/hala-arar-9931a615b/





